os:
  - linux
matrix:
  include:
    - language: perl6
      perl6: latest
      install:
        - rakudobrew build-zef
        - zef install JSON::Fast
      script: prove --ext=.t -r --exec=perl6 perl6
