language:
  - minimal

services:
  - docker

install:
  - docker pull jjmerelo/test-perl6

script: docker run -t --entrypoint="/bin/sh" -v $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6 -c "zef update && zef install JSON::Fast && prove -r --exec=perl6 perl6"
